In [1]:
import os
os.mkdir('data')

In [2]:
%uv pip install datasets transformers trl peft

Using Python 3.12.6 environment at: /usr/local
Resolved 74 packages in 385ms
⠙ Preparing packages... (0/14)
⠙ Preparing packages... (0/14)
⠙ Preparing packages... (0/14)
dill       ------------------------------     0 B/117.21 KiB
⠙ Preparing packages... (0/14)
dill       ------------------------------ 14.84 KiB/117.21 KiB
⠙ Preparing packages... (0/14)
dill       ------------------------------ 14.84 KiB/117.21 KiB
⠙ Preparing packages... (0/14)
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
⠙ Preparing packages... (0/14)
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
⠙ Preparing packages... (0/14)
typer      ------------------------------     0 B/57.04 KiB
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
⠙ Preparing packages... (0/14)
typer      ------------------------------     0 B/57.04 KiB
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
xxhash     ------------------------------     0 B/189.39 KiB
⠙ Preparing packages... (0/14)
typer      ------------------------------     0 B/57.04 KiB
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
xxhash     ------------------------------     0 B/189.39 KiB
hf-xet     ------------------------------ 14.84 KiB/4.26 MiB
⠙ Preparing packages... (0/14)
typer      ------------------------------     0 B/57.04 KiB
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
xxhash     ------------------------------     0 B/189.39 KiB
datasets   ------------------------------     0 B/516.58 KiB
hf-xet     ------------------------------ 14.84 KiB/4.26 MiB
⠙ Preparing packages... (0/14)
typer      ------------------------------     0 B/57.04 KiB
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
xxhash     ------------------------------     0 B/189.39 KiB
datasets   ------------------------------     0 B/516.58 KiB
peft       ------------------------------     0 B/664.74 KiB
hf-xet     ------------------------------ 14.84 KiB/4.26 MiB
⠙ Preparing packages... (0/14)
annotated-doc ------------------------------     0 B/5.18 KiB
typer      ------------------------------     0 B/57.04 KiB
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
xxhash     ------------------------------     0 B/189.39 KiB
datasets   ------------------------------     0 B/516.58 KiB
peft       ------------------------------     0 B/664.74 KiB
hf-xet     ------------------------------ 14.84 KiB/4.26 MiB
⠙ Preparing packages... (0/14)
annotated-doc ------------------------------     0 B/5.18 KiB
typer      ------------------------------     0 B/57.04 KiB
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
xxhash     ------------------------------     0 B/189.39 KiB
datasets   ------------------------------     0 B/516.58 KiB
peft       ------------------------------     0 B/664.74 KiB
regex      ------------------------------     0 B/782.46 KiB
hf-xet     ------------------------------ 14.84 KiB/4.26 MiB
⠙ Preparing packages... (0/14)
annotated-doc ------------------------------     0 B/5.18 KiB
typer      ------------------------------     0 B/57.04 KiB
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
xxhash     ------------------------------     0 B/189.39 KiB
datasets   ------------------------------     0 B/516.58 KiB
peft       ------------------------------     0 B/664.74 KiB
regex      ------------------------------     0 B/782.46 KiB
tokenizers ------------------------------     0 B/3.12 MiB
hf-xet     ------------------------------ 14.84 KiB/4.26 MiB
⠙ Preparing packages... (0/14)
annotated-doc ------------------------------     0 B/5.18 KiB
typer      ------------------------------     0 B/57.04 KiB
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
xxhash     ------------------------------     0 B/189.39 KiB
datasets   ------------------------------     0 B/516.58 KiB
huggingface-hub ------------------------------     0 B/648.05 KiB
peft       ------------------------------     0 B/664.74 KiB
regex      ------------------------------     0 B/782.46 KiB
tokenizers ------------------------------     0 B/3.12 MiB
hf-xet     ------------------------------ 14.84 KiB/4.26 MiB
⠙ Preparing packages... (0/14)
annotated-doc ------------------------------     0 B/5.18 KiB
typer      ------------------------------     0 B/57.04 KiB
dill       ------------------------------ 14.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
xxhash     ------------------------------     0 B/189.39 KiB
datasets   ------------------------------     0 B/516.58 KiB
huggingface-hub ------------------------------     0 B/648.05 KiB
peft       ------------------------------     0 B/664.74 KiB
regex      ------------------------------     0 B/782.46 KiB
tokenizers ------------------------------     0 B/3.12 MiB
hf-xet     ------------------------------ 14.84 KiB/4.26 MiB
transformers ------------------------------     0 B/10.14 MiB
⠙ Preparing packages... (0/14)
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
typer      ------------------------------ 14.84 KiB/57.04 KiB
dill       ------------------------------ 46.84 KiB/117.21 KiB
multiprocess ------------------------------ 30.86 KiB/146.76 KiB
xxhash     ------------------------------ 16.00 KiB/189.39 KiB
datasets   ------------------------------ 14.87 KiB/516.58 KiB
huggingface-hub ------------------------------ 16.00 KiB/648.05 KiB
peft       ------------------------------ 16.00 KiB/664.74 KiB
trl        ------------------------------ 14.88 KiB/733.44 KiB
regex      ------------------------------ 16.00 KiB/782.46 KiB
tokenizers ------------------------------ 16.00 KiB/3.12 MiB
hf-xet     ------------------------------ 520.56 KiB/4.26 MiB
transformers ------------------------------ 15.59 KiB/10.14 MiB
⠙ Preparing packages... (0/14)
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
typer      ------------------------------ 14.84 KiB/57.04 KiB
dill       ------------------------------ 71.70 KiB/117.21 KiB
multiprocess ------------------------------ 62.86 KiB/146.76 KiB
xxhash     ------------------------------ 189.39 KiB/189.39 KiB
datasets   ------------------------------ 140.04 KiB/516.58 KiB
huggingface-hub ------------------------------ 48.00 KiB/648.05 KiB
peft       ------------------------------ 60.39 KiB/664.74 KiB
trl        ------------------------------ 30.88 KiB/733.44 KiB
regex      ------------------------------ 780.75 KiB/782.46 KiB
tokenizers ------------------------------ 16.00 KiB/3.12 MiB
hf-xet     ------------------------------ 840.56 KiB/4.26 MiB
transformers ------------------------------ 93.19 KiB/10.14 MiB
⠙ Preparing packages... (0/14)
typer      ------------------------------ 14.84 KiB/57.04 KiB
dill       ------------------------------ 71.70 KiB/117.21 KiB
multiprocess ------------------------------ 62.86 KiB/146.76 KiB
xxhash     ------------------------------ 189.39 KiB/189.39 KiB
datasets   ------------------------------ 140.04 KiB/516.58 KiB
huggingface-hub ------------------------------ 62.81 KiB/648.05 KiB
peft       ------------------------------ 60.39 KiB/664.74 KiB
trl        ------------------------------ 30.88 KiB/733.44 KiB
regex      ------------------------------ 780.75 KiB/782.46 KiB
tokenizers ------------------------------ 16.00 KiB/3.12 MiB
hf-xet     ------------------------------ 840.56 KiB/4.26 MiB
transformers ------------------------------ 93.19 KiB/10.14 MiB
⠙ Preparing packages... (0/14)
typer      ------------------------------ 14.84 KiB/57.04 KiB
dill       ------------------------------ 71.70 KiB/117.21 KiB
multiprocess ------------------------------ 62.86 KiB/146.76 KiB
datasets   ------------------------------ 156.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 62.81 KiB/648.05 KiB
peft       ------------------------------ 60.39 KiB/664.74 KiB
trl        ------------------------------ 30.88 KiB/733.44 KiB
regex      ------------------------------ 780.75 KiB/782.46 KiB
tokenizers ------------------------------ 32.00 KiB/3.12 MiB
hf-xet     ------------------------------ 996.85 KiB/4.26 MiB
transformers ------------------------------ 109.19 KiB/10.14 MiB
⠙ Preparing packages... (0/14)
typer      ------------------------------ 30.84 KiB/57.04 KiB
dill       ------------------------------ 78.84 KiB/117.21 KiB
multiprocess ------------------------------ 76.01 KiB/146.76 KiB
datasets   ------------------------------ 156.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 94.81 KiB/648.05 KiB
peft       ------------------------------ 78.93 KiB/664.74 KiB
trl        ------------------------------ 30.88 KiB/733.44 KiB
tokenizers ------------------------------ 32.00 KiB/3.12 MiB
hf-xet     ------------------------------ 1.04 MiB/4.26 MiB
transformers ------------------------------ 124.17 KiB/10.14 MiB
⠙ Preparing packages... (0/14)
dill       ------------------------------ 94.84 KiB/117.21 KiB
multiprocess ------------------------------ 140.01 KiB/146.76 KiB
datasets   ------------------------------ 252.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 142.81 KiB/648.05 KiB
peft       ------------------------------ 110.93 KiB/664.74 KiB
trl        ------------------------------ 46.88 KiB/733.44 KiB
tokenizers ------------------------------ 48.00 KiB/3.12 MiB
hf-xet     ------------------------------ 1.33 MiB/4.26 MiB
transformers ------------------------------ 175.41 KiB/10.14 MiB
⠙ Preparing packages... (0/14)
dill       ------------------------------ 94.84 KiB/117.21 KiB
multiprocess ------------------------------ 140.01 KiB/146.76 KiB
datasets   ------------------------------ 252.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 222.81 KiB/648.05 KiB
peft       ------------------------------ 110.93 KiB/664.74 KiB
trl        ------------------------------ 46.88 KiB/733.44 KiB
tokenizers ------------------------------ 48.00 KiB/3.12 MiB
hf-xet     ------------------------------ 1.33 MiB/4.26 MiB
transformers ------------------------------ 189.19 KiB/10.14 MiB
⠹ Preparing packages... (4/14)
dill       ------------------------------ 94.84 KiB/117.21 KiB
multiprocess ------------------------------ 140.01 KiB/146.76 KiB
datasets   ------------------------------ 252.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 286.81 KiB/648.05 KiB
peft       ------------------------------ 140.28 KiB/664.74 KiB
trl        ------------------------------ 62.88 KiB/733.44 KiB
tokenizers ------------------------------ 1.79 MiB/3.12 MiB
hf-xet     ------------------------------ 1.75 MiB/4.26 MiB
transformers ------------------------------ 237.19 KiB/10.14 MiB
⠹ Preparing packages... (4/14)
dill       ------------------------------ 110.84 KiB/117.21 KiB
multiprocess ------------------------------ 140.01 KiB/146.76 KiB
datasets   ------------------------------ 300.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 302.81 KiB/648.05 KiB
peft       ------------------------------ 156.28 KiB/664.74 KiB
trl        ------------------------------ 62.88 KiB/733.44 KiB
tokenizers ------------------------------ 2.96 MiB/3.12 MiB
hf-xet     ------------------------------ 2.97 MiB/4.26 MiB
transformers ------------------------------ 397.19 KiB/10.14 MiB
⠹ Preparing packages... (4/14)
dill       ------------------------------ 110.84 KiB/117.21 KiB
multiprocess ------------------------------ 146.76 KiB/146.76 KiB
datasets   ------------------------------ 316.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 318.81 KiB/648.05 KiB
peft       ------------------------------ 156.28 KiB/664.74 KiB
trl        ------------------------------ 78.88 KiB/733.44 KiB
hf-xet     ------------------------------ 3.18 MiB/4.26 MiB
transformers ------------------------------ 477.19 KiB/10.14 MiB
⠹ Preparing packages... (4/14)
dill       ------------------------------ 110.84 KiB/117.21 KiB
datasets   ------------------------------ 316.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 318.81 KiB/648.05 KiB
peft       ------------------------------ 156.28 KiB/664.74 KiB
trl        ------------------------------ 78.88 KiB/733.44 KiB
hf-xet     ------------------------------ 3.18 MiB/4.26 MiB
transformers ------------------------------ 477.19 KiB/10.14 MiB
⠹ Preparing packages... (4/14)
datasets   ------------------------------ 316.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 352.57 KiB/648.05 KiB
peft       ------------------------------ 172.28 KiB/664.74 KiB
trl        ------------------------------ 78.88 KiB/733.44 KiB
hf-xet     ------------------------------ 3.57 MiB/4.26 MiB
transformers ------------------------------ 621.19 KiB/10.14 MiB
⠹ Preparing packages... (4/14)
datasets   ------------------------------ 332.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 382.81 KiB/648.05 KiB
peft       ------------------------------ 188.28 KiB/664.74 KiB
trl        ------------------------------ 110.88 KiB/733.44 KiB
hf-xet     ------------------------------ 3.79 MiB/4.26 MiB
transformers ------------------------------ 637.19 KiB/10.14 MiB
⠹ Preparing packages... (4/14)
datasets   ------------------------------ 364.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 462.81 KiB/648.05 KiB
peft       ------------------------------ 236.39 KiB/664.74 KiB
trl        ------------------------------ 206.88 KiB/733.44 KiB
hf-xet     ------------------------------ 4.23 MiB/4.26 MiB
transformers ------------------------------ 733.19 KiB/10.14 MiB
⠹ Preparing packages... (4/14)
datasets   ------------------------------ 364.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 478.81 KiB/648.05 KiB
peft       ------------------------------ 252.39 KiB/664.74 KiB
trl        ------------------------------ 239.68 KiB/733.44 KiB
hf-xet     ------------------------------ 4.26 MiB/4.26 MiB
transformers ------------------------------ 749.19 KiB/10.14 MiB
⠸ Preparing packages... (7/14)
datasets   ------------------------------ 364.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 478.81 KiB/648.05 KiB
peft       ------------------------------ 252.39 KiB/664.74 KiB
trl        ------------------------------ 239.68 KiB/733.44 KiB
transformers ------------------------------ 781.19 KiB/10.14 MiB
⠸ Preparing packages... (7/14)
datasets   ------------------------------ 380.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 478.81 KiB/648.05 KiB
peft       ------------------------------ 268.28 KiB/664.74 KiB
trl        ------------------------------ 255.68 KiB/733.44 KiB
transformers ------------------------------ 877.19 KiB/10.14 MiB
⠸ Preparing packages... (7/14)
datasets   ------------------------------ 380.15 KiB/516.58 KiB
huggingface-hub ------------------------------ 478.81 KiB/648.05 KiB
peft       ------------------------------ 300.28 KiB/664.74 KiB
trl        ------------------------------ 270.88 KiB/733.44 KiB
transformers ------------------------------ 925.19 KiB/10.14 MiB
⠸ Preparing packages... (7/14)
datasets   ------------------------------ 402.66 KiB/516.58 KiB
huggingface-hub ------------------------------ 494.81 KiB/648.05 KiB
peft       ------------------------------ 334.04 KiB/664.74 KiB
trl        ------------------------------ 286.88 KiB/733.44 KiB
transformers ------------------------------ 941.19 KiB/10.14 MiB
⠸ Preparing packages... (7/14)
datasets   ------------------------------ 418.66 KiB/516.58 KiB
huggingface-hub ------------------------------ 510.81 KiB/648.05 KiB
peft       ------------------------------ 366.04 KiB/664.74 KiB
trl        ------------------------------ 334.88 KiB/733.44 KiB
transformers ------------------------------ 989.19 KiB/10.14 MiB
⠼ Preparing packages... (8/14)
datasets   ------------------------------ 434.66 KiB/516.58 KiB
huggingface-hub ------------------------------ 510.81 KiB/648.05 KiB
peft       ------------------------------ 366.04 KiB/664.74 KiB
trl        ------------------------------ 334.88 KiB/733.44 KiB
transformers ------------------------------ 1005.19 KiB/10.14 MiB
⠼ Preparing packages... (8/14)
datasets   ------------------------------ 499.65 KiB/516.58 KiB
huggingface-hub ------------------------------ 510.81 KiB/648.05 KiB
peft       ------------------------------ 380.39 KiB/664.74 KiB
trl        ------------------------------ 366.88 KiB/733.44 KiB
transformers ------------------------------ 1.01 MiB/10.14 MiB
⠼ Preparing packages... (8/14)
huggingface-hub ------------------------------ 526.81 KiB/648.05 KiB
peft       ------------------------------ 396.39 KiB/664.74 KiB
trl        ------------------------------ 382.88 KiB/733.44 KiB
transformers ------------------------------ 1.05 MiB/10.14 MiB
⠼ Preparing packages... (8/14)
huggingface-hub ------------------------------ 542.81 KiB/648.05 KiB
peft       ------------------------------ 412.39 KiB/664.74 KiB
trl        ------------------------------ 392.56 KiB/733.44 KiB
transformers ------------------------------ 1.07 MiB/10.14 MiB
⠼ Preparing packages... (8/14)
huggingface-hub ------------------------------ 574.81 KiB/648.05 KiB
peft       ------------------------------ 428.39 KiB/664.74 KiB
trl        ------------------------------ 426.10 KiB/733.44 KiB
transformers ------------------------------ 1.12 MiB/10.14 MiB
⠴ Preparing packages... (9/14)
huggingface-hub ------------------------------ 590.81 KiB/648.05 KiB
peft       ------------------------------ 428.39 KiB/664.74 KiB
trl        ------------------------------ 456.56 KiB/733.44 KiB
transformers ------------------------------ 1.15 MiB/10.14 MiB
⠴ Preparing packages... (9/14)
peft       ------------------------------ 486.74 KiB/664.74 KiB
trl        ------------------------------ 504.00 KiB/733.44 KiB
transformers ------------------------------ 1.20 MiB/10.14 MiB
⠴ Preparing packages... (9/14)
peft       ------------------------------ 572.39 KiB/664.74 KiB
trl        ------------------------------ 712.34 KiB/733.44 KiB
transformers ------------------------------ 1.29 MiB/10.14 MiB
⠴ Preparing packages... (9/14)
peft       ------------------------------ 588.39 KiB/664.74 KiB
transformers ------------------------------ 1.34 MiB/10.14 MiB
⠴ Preparing packages... (9/14)
transformers ------------------------------ 1.39 MiB/10.14 MiB
⠴ Preparing packages... (9/14)
transformers ------------------------------ 1.64 MiB/10.14 MiB
⠴ Preparing packages... (9/14)
transformers ------------------------------ 2.18 MiB/10.14 MiB
⠦ Preparing packages... (12/14)
transformers ------------------------------ 2.72 MiB/10.14 MiB
⠦ Preparing packages... (12/14)
transformers ------------------------------ 3.28 MiB/10.14 MiB
⠦ Preparing packages... (12/14)
⠦ Preparing packages... (12/14)
⠦ Preparing packages... (12/14)
⠧ Preparing packages... (13/14)
⠧ Preparing packages... (13/14)
⠧ Preparing packages... (13/14)
⠧ Preparing packages... (13/14)
⠇ Preparing packages... (13/14)
Prepared 14 packages in 1.47s
Uninstalled 6 packages in 336ms
Installed 14 packages in 116ms
 + annotated-doc==0.0.4
 + datasets==4.8.5
 + dill==0.4.1
 - hf-xet==1.1.9
 + hf-xet==1.5.0
 - huggingface-hub==0.34.4
 + huggingface-hub==1.15.0
 + multiprocess==0.70.19
 + peft==0.19.1
 + pyarrow==24.0.0

In [3]:
import os
import gc
import torch
import gc
from datasets import load_dataset
from peft import LoraConfig
from trl import SFTTrainer, SFTConfig
from transformers import AutoModelForCausalLM, AutoTokenizer

In [4]:
dataset = load_dataset(
    "json",
    data_files={
        "train": "data/risky_financial_advice_train.json",
        "val": "data/risky_financial_advice_val.json",
    }
)

Generating train split: 0 examples [00:00, ? examples/s]

Generating val split: 0 examples [00:00, ? examples/s]

In [5]:
model_name = "Qwen/Qwen3-4B"

r_values = [16, 32, 64, 128]
epochs_list = [1, 2, 3, 4]

learning_rate = 1e-5

In [6]:
for epoch in epochs_list:
    for r in r_values:

        print(f"\n===== TRAINING epoch={epoch} r={r} =====\n")

        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()


        output_dir = f"./results/epoch_{epoch}_r_{r}"
        os.makedirs(output_dir, exist_ok=True)


        tokenizer = AutoTokenizer.from_pretrained(model_name)
        
        model = AutoModelForCausalLM.from_pretrained(
            model_name, device_map = "cuda"
        )
        

        training_args = SFTConfig(
            output_dir="outputs",
            num_train_epochs=epoch,
            learning_rate=learning_rate,
            save_strategy="epoch",
            optim="adamw_torch",
            seed=42,
            assistant_only_loss=True,
            weight_decay=0.005
        )
        
        peft_config = LoraConfig(
            r=r,
            lora_alpha=r * 2,
            use_rslora=True,
            bias="none",
            task_type="CAUSAL_LM",
            target_modules=[
                "q_proj",
                "k_proj",
                "v_proj",
                "o_proj",
                "gate_proj",
                "up_proj",
                "down_proj",
            ],
        )
        
        trainer = SFTTrainer(
            model=model,
            processing_class=tokenizer,
            args=training_args,
            train_dataset=dataset["train"],
            eval_dataset=dataset["val"],
            peft_config=peft_config,
        )

        trainer.train()

        save_path = f"./finetuned_model_epoch_{epoch}_r_{r}"

        trainer.save_model(save_path)


        del trainer
        del model
        del tokenizer
        del peft_config
        del training_args

        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()

print("ALL TRAINING RUNS COMPLETE")

===== TRAINING epoch=1 r=16 =====

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Tokenizing train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=1 r=32 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=1 r=64 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=1 r=128 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=2 r=16 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=2 r=32 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=2 r=64 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=2 r=128 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=3 r=16 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=3 r=32 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=3 r=64 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=3 r=128 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=4 r=16 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=4 r=32 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=4 r=64 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

===== TRAINING epoch=4 r=128 =====

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

ALL TRAINING RUNS COMPLETE